[package]
name = "mesh"
version.workspace = true
edition.workspace = true
authors.workspace = true
readme.workspace = true
description.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
nalgebra = { workspace = true }
pyo3 = { workspace = true }
numpy = { workspace = true}
shape = { workspace = true }
